version: 2

sources:
  - name: raw
    database: my-project-1404-493313
    schema: gz_raw_data
    description: Raw dataset loaded from Greenweez source systems

    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Sales of Greenweez / we have on row per product_id found in each orders_id
        config:
          loaded_at_field: "CAST(date_date AS TIMESTAMP)"
          freshness:
            warn_after:
              count: 90
              period: day

        columns:
          - name: date_date
            description: Date of purchase

          - name: orders_id
            description: Unique order identifier

          - name: pdt_id
            description: Product identifier

          - name: revenue
            description: Revenue amount

          - name: quantity
            description: Quantity sold
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

      - name: product
        identifier: raw_gz_product
        description: Product master data

        columns:
          - name: products_id
            description: Unique product identifier
            tests: 
              - not_null
              - unique
              
              

          - name: purchse_price
            description: Original purchase price

      - name: ship
        identifier: raw_gz_ship
        description: Shipping and logistics information

        columns:
          - name: orders_id
            description: Order identifier
            tests:
              - not_null
              - unique
              

          - name: shipping_fee
            description: Shipping fee charged

          - name: ship_cost
            description: Shipping cost